name: Playwright Tests 

on: [push, pull_request]   # Run when code is pushed or PR is created

jobs:
  test:
    runs-on: ubuntu-latest   # GitHub provides a Linux VM

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=dot
